Remove and skip active flows
simplic/simplic-flow pull request #42
Opened 2018-11-15 20:40 UTC by simplicbe

2018-11-19 06:47 UTC, yvz5 requested changes

2018-11-19 06:47 UTC, yvz5 commented on src/Simplic.Flow.Data.Memory/FlowInstanceMemoryRepository.cs
> +            throw new NotImplementedException();
forgot to implement ?

2018-12-12 12:45 UTC, simplicbe commented on src/Simplic.Flow.Data.Memory/FlowInstanceMemoryRepository.cs
> +            throw new NotImplementedException();
Will be completly reimplemented

2018-12-12 12:45 UTC, yvz5 approved these changes

2018-12-12 12:46 UTC, merged