WIP F added isactive flag
simplic/simplic-flow pull request #47
Opened 2019-03-12 15:40 UTC by LarsTepper

2019-03-12 15:41 UTC, LarsTepper commented
Only ui needed to activate an deactivate flows! very usefull for debugging

2019-03-12 15:49 UTC, simplicbe commented on src/Simplic.Flow.Service/FlowService.cs
> +            foreach (var flowConfiguration in flowConfigurations.Where(f=>f.IsActive))
Strg + K + D

2019-03-12 15:50 UTC, simplicbe requested changes
Reset line ending

2019-03-12 18:16 UTC, yvz5 requested changes
`src/Simplic.FlowInstance.Service/FlowInstanceService.cs`
why is this file changed ? probably line ending style changed.

2019-03-28 09:45 UTC, yvz5 commented
merged into #50

2019-03-28 09:45 UTC, closed without merging