Adds the ability to view a node documentation via a node context menu entry. (~2631)
simplic/simplic-flow pull request #81
Opened 2022-03-04 13:24 UTC by juliusfunke

2022-03-04 15:14 UTC, juliusfunke commented
Problem: This yields an error when trying to edit a flow until the DocumentationUrl node definition attribute of all nodes in the flow are set. So we can't set the attribute over time as we add the XAML documentation to the node classes, we have to add the attribute to all nodes right away.
I think the best solution is to use the GitHub API the same way we did for the Sybase update last year and add the attribute this way because the URL can be auto-generated in most cases. We would only need to change the URL attribute manually in some cases. Also we could add a basic node documentation template for all nodes when we are at it.

2022-03-08 11:24 UTC, simplicbe requested changes

2022-03-08 11:24 UTC, simplicbe commented on src/Simplic.Flow.Editor.UI/ViewModel/Node/NodeViewModel.cs
> +        private bool CheckURLValid(string url)
Add description here.

2022-03-08 11:24 UTC, simplicbe commented on src/Simplic.Flow.Editor.UI/ViewModel/Node/NodeViewModel.cs
> +            MessageBox.Show(localizationService.Translate("flow_documentation_not_found"));
All message boxes require:

* Title
* Message
* Button
* Image

2022-03-08 12:51 UTC, simplicbe commented on src/Simplic.Flow.Editor.Definition/Model/NodeDefinition.cs
> +        /// <summary>
```suggestion

        /// <summary>
```

2022-03-08 12:52 UTC, simplicbe requested changes

2022-03-08 12:52 UTC, simplicbe commented on src/Simplic.Flow.Editor.UI/Resources.xaml
> +                    <MenuItem Header="Show documentation" Command="{Binding ShowDocumentationCommand}"/>
Localization

2022-03-08 12:52 UTC, simplicbe commented on src/Simplic.Flow.Editor.UI/Resources.xaml
> +                    <MenuItem Header="Show documentation" Command="{Binding ShowDocumentationCommand}"/>
Localization

2022-03-08 14:19 UTC, simplicbe commented on src/Simplic.Flow/Attribute/NodeDefinitionAttribute.cs
> +        /// <summary>
```suggestion

        /// <summary>
```

2022-03-08 14:19 UTC, merged